/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cl.unibiblioduocuc.vista;

import cl.unibiblioduocuc.controlador.ContLogin;
import cl.unibiblioduocuc.modelo.DataBase;
import cl.unibiblioduocuc.utils.Utils;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Gabriel
 */
public class JF_Login extends javax.swing.JFrame {
    
    private DataBase db;
    
    /**
     * Creates new form Login
     */
    public JF_Login() {
        initComponents();
        Utils.cambiarIconoJFrame(this);
        
        /* Inicializaciones */
        this.db = new DataBase();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel_login = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTxt_correo = new javax.swing.JTextField();
        jBttn_login = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPass_contrasenna = new javax.swing.JPasswordField();
        jPanel_logo = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Unibiblio - DuocUC");
        setMinimumSize(new java.awt.Dimension(786, 693));
        setPreferredSize(new java.awt.Dimension(786, 693));
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel_login.setBackground(new java.awt.Color(0, 51, 102));
        jPanel_login.setMinimumSize(new java.awt.Dimension(470, 33));
        jPanel_login.setPreferredSize(new java.awt.Dimension(100, 100));
        jPanel_login.setLayout(new java.awt.GridBagLayout());

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));
        jPanel1.setMinimumSize(new java.awt.Dimension(100, 33));
        jPanel1.setPreferredSize(new java.awt.Dimension(100, 100));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Open Sans", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(229, 229, 229));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("¡Inicie sesión!");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.setMinimumSize(new java.awt.Dimension(100, 33));
        jLabel1.setPreferredSize(new java.awt.Dimension(100, 33));
        jPanel1.add(jLabel1, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.8;
        jPanel_login.add(jPanel1, gridBagConstraints);

        jPanel2.setBackground(new java.awt.Color(0, 51, 102));
        jPanel2.setPreferredSize(new java.awt.Dimension(335, 592));
        java.awt.GridBagLayout jPanel2Layout = new java.awt.GridBagLayout();
        jPanel2Layout.columnWidths = new int[] {0, 20, 0, 20, 0, 20, 0, 20, 0, 20, 0};
        jPanel2Layout.rowHeights = new int[] {0, 20, 0, 20, 0};
        jPanel2.setLayout(jPanel2Layout);

        jLabel2.setForeground(new java.awt.Color(229, 229, 229));
        jLabel2.setText("Correo electrónico:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel2.add(jLabel2, gridBagConstraints);

        jTxt_correo.setMinimumSize(new java.awt.Dimension(64, 30));
        jTxt_correo.setName(""); // NOI18N
        jTxt_correo.setPreferredSize(new java.awt.Dimension(70, 35));
        jTxt_correo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTxt_correoKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        jPanel2.add(jTxt_correo, gridBagConstraints);

        jBttn_login.setText("Ingresar");
        jBttn_login.setPreferredSize(new java.awt.Dimension(75, 30));
        jBttn_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBttn_loginActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel2.add(jBttn_login, gridBagConstraints);

        jLabel3.setForeground(new java.awt.Color(229, 229, 229));
        jLabel3.setText("Contraseña:");
        jLabel3.setMinimumSize(new java.awt.Dimension(62, 20));
        jLabel3.setPreferredSize(new java.awt.Dimension(70, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel2.add(jLabel3, gridBagConstraints);

        jPass_contrasenna.setPreferredSize(new java.awt.Dimension(70, 35));
        jPass_contrasenna.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPass_contrasennaKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel2.add(jPass_contrasenna, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.8;
        jPanel_login.add(jPanel2, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.4;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(jPanel_login, gridBagConstraints);

        jPanel_logo.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_logo.setName(""); // NOI18N
        jPanel_logo.setPreferredSize(new java.awt.Dimension(100, 100));
        jPanel_logo.setLayout(new java.awt.BorderLayout());

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cl/unibiblioduocuc/img/logo-full-white.png"))); // NOI18N
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel_logo.add(jLabel4, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.6;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(jPanel_logo, gridBagConstraints);

        setSize(new java.awt.Dimension(850, 700));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBttn_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBttn_loginActionPerformed
        String password = String.valueOf(jPass_contrasenna.getPassword());
        if (jTxt_correo.getText().isEmpty() && password.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Debe ingresar sus credenciales.", "Error de ingreso", JOptionPane.ERROR_MESSAGE);
        } else {
            ContLogin cl = new ContLogin(db);
         cl.redigirLogin(this, db, cl.validarLogin(Utils.obtenerInput(jTxt_correo), Utils.obtenerInputPassword(jPass_contrasenna), db));
        }
  
        
        
    }//GEN-LAST:event_jBttn_loginActionPerformed

    private void jTxt_correoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxt_correoKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jBttn_login.doClick();
        }
    }//GEN-LAST:event_jTxt_correoKeyPressed

    private void jPass_contrasennaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPass_contrasennaKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jBttn_login.doClick();
        }
    }//GEN-LAST:event_jPass_contrasennaKeyPressed

    /* Metodos customizados */
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JF_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JF_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JF_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JF_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JF_Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBttn_login;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel_login;
    private javax.swing.JPanel jPanel_logo;
    private javax.swing.JPasswordField jPass_contrasenna;
    private javax.swing.JTextField jTxt_correo;
    // End of variables declaration//GEN-END:variables
}
