package cl.unibiblioduocuc.vista;

import cl.unibiblioduocuc.controlador.ControladorPrincipal;
import cl.unibiblioduocuc.modelo.Bibliotecario;
import cl.unibiblioduocuc.modelo.Libro;
import cl.unibiblioduocuc.modelo.bd.TestBD;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Desktop;
import java.awt.event.KeyEvent;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JEditorPane;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.table.DefaultTableModel;
import cl.unibiblioduocuc.utils.Utils;

/**
 *
 * @author Gabriel Serrano
 */
public class VistaPrincipal extends javax.swing.JFrame {

    private VistaLogin vistaLogin;
    private Bibliotecario biblioLogeado;
    private TestBD bd;
    private ArrayList<JRadioButton> radioButtons;
    private int libroId = -1;

    //Crea colores
    private Color primaryBg = new Color(229, 229, 229);
    private Color secondaryBg = new Color(0, 51, 102);
    private Color secondaryBtn = new Color(0, 34, 68);

    /**
     * Crea la vista principal con los datos de login
     *
     * @param biblioLogeado
     */
    public VistaPrincipal(Bibliotecario biblioLogeado) {
        this.radioButtons = new ArrayList<JRadioButton>();
        this.bd = new TestBD();

        initComponents();
        fillAllBooks();
        enlistarRadButtons(jRadBtn_Titulo, jRadBtn_Autor, jRadBtn_Isbn);

        //Cambiar ícono de ventana
        Utils.cambiarIconoFrame(this);

        //Setea empleado logeado
        this.biblioLogeado = biblioLogeado;

        //Muestra en vista nombre del empelado
        setNombreEmpleadoUI();
    }

    /**
     * Creates new form VistaLibros
     *
     */
    public VistaPrincipal() {
        this.radioButtons = new ArrayList<JRadioButton>();
        this.bd = new TestBD();

        initComponents();
        fillAllBooks();
        enlistarRadButtons(jRadBtn_Titulo, jRadBtn_Autor, jRadBtn_Isbn);

        //Cambiar ícono de ventana
        try {
            ImageIcon icon = new ImageIcon(getClass().getResource("/cl/unibiblioduocuc/img/logo-small.png"));
            setIconImage(icon.getImage());
        } catch (Exception ex) {
        }

        //Setear nombre del empelado
        this.biblioLogeado = bd.obtenerBibliotecario("juan.perez@biblioteca.com");
        setNombreEmpleadoUI();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jMenuItem1 = new javax.swing.JMenuItem();
        jBtnGroup_SearchBar_Libros = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel_NomEmpleado = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanelBtn_Libros = new javax.swing.JPanel();
        jBtn_Libros = new javax.swing.JLabel();
        jPanelBtn_Prestamos = new javax.swing.JPanel();
        jBtn_Prestamos = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jBtn_Salir = new javax.swing.JLabel();
        jParentPanel_VPrincipal = new javax.swing.JPanel();
        jPanel_Libros = new javax.swing.JPanel();
        jPanel_SearchBarLibros = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTxt_InputSearch = new javax.swing.JTextField();
        jBtn_SubmitSearch = new javax.swing.JButton();
        jRadBtn_Titulo = new javax.swing.JRadioButton();
        jRadBtn_Autor = new javax.swing.JRadioButton();
        jRadBtn_Isbn = new javax.swing.JRadioButton();
        jPanel_GestionLibros = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jBtn_agregar = new javax.swing.JButton();
        jBtn_editar = new javax.swing.JButton();
        jBtn_eliminar = new javax.swing.JButton();
        jPanel_CatalogoLibros = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_CatLibros = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jPanel_Prestamos = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItem9 = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu_Help = new javax.swing.JMenu();
        jMenuItem_About = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("UniBiblio Duoc UC - Libros");
        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));
        setResizable(false);
        setSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel1.setLayout(new java.awt.GridBagLayout());

        jPanel3.setBackground(new java.awt.Color(0, 51, 102));
        jPanel3.setMinimumSize(new java.awt.Dimension(143, 40));
        jPanel3.setPreferredSize(new java.awt.Dimension(150, 100));
        jPanel3.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Open Sans", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(229, 229, 229));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Bienvenido");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        jPanel3.add(jLabel1, gridBagConstraints);

        jLabel_NomEmpleado.setFont(new java.awt.Font("Open Sans", 1, 14)); // NOI18N
        jLabel_NomEmpleado.setForeground(new java.awt.Color(229, 229, 229));
        jLabel_NomEmpleado.setText("nombre_empelado");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        jPanel3.add(jLabel_NomEmpleado, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.1;
        jPanel1.add(jPanel3, gridBagConstraints);

        jPanel5.setBackground(new java.awt.Color(0, 51, 102));
        jPanel5.setMinimumSize(new java.awt.Dimension(143, 0));
        jPanel5.setPreferredSize(new java.awt.Dimension(150, 0));
        jPanel5.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.TRAILING, 0, 50));

        jPanelBtn_Libros.setBackground(new java.awt.Color(229, 229, 229));
        jPanelBtn_Libros.setName("jPanelBtn_Libros"); // NOI18N
        jPanelBtn_Libros.setPreferredSize(new java.awt.Dimension(178, 50));
        jPanelBtn_Libros.setLayout(new java.awt.BorderLayout());

        jBtn_Libros.setFont(new java.awt.Font("Open Sans", 1, 16)); // NOI18N
        jBtn_Libros.setForeground(new java.awt.Color(0, 51, 102));
        jBtn_Libros.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jBtn_Libros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cl/unibiblioduocuc/img/jBtn_Libros-icon-fill.png"))); // NOI18N
        jBtn_Libros.setText("Libros");
        jBtn_Libros.setName("jBtn_Libros"); // NOI18N
        jBtn_Libros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtn_LibrosMouseClicked(evt);
            }
        });
        jPanelBtn_Libros.add(jBtn_Libros, java.awt.BorderLayout.CENTER);

        jPanel5.add(jPanelBtn_Libros);

        jPanelBtn_Prestamos.setBackground(new java.awt.Color(0, 34, 68));
        jPanelBtn_Prestamos.setName("jPanelBtn_Prestamos"); // NOI18N
        jPanelBtn_Prestamos.setPreferredSize(new java.awt.Dimension(178, 50));
        jPanelBtn_Prestamos.setLayout(new java.awt.BorderLayout());

        jBtn_Prestamos.setBackground(new java.awt.Color(0, 38, 76));
        jBtn_Prestamos.setFont(new java.awt.Font("Open Sans", 1, 16)); // NOI18N
        jBtn_Prestamos.setForeground(new java.awt.Color(229, 229, 229));
        jBtn_Prestamos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jBtn_Prestamos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cl/unibiblioduocuc/img/jBtn_Prestamos-icon-blank.png"))); // NOI18N
        jBtn_Prestamos.setText("Préstamos");
        jBtn_Prestamos.setName("jBtn_Prestamos"); // NOI18N
        jBtn_Prestamos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtn_PrestamosMouseClicked(evt);
            }
        });
        jPanelBtn_Prestamos.add(jBtn_Prestamos, java.awt.BorderLayout.CENTER);

        jPanel5.add(jPanelBtn_Prestamos);

        jPanel9.setBackground(new java.awt.Color(0, 34, 68));
        jPanel9.setPreferredSize(new java.awt.Dimension(178, 50));
        jPanel9.setLayout(new java.awt.BorderLayout());

        jBtn_Salir.setBackground(new java.awt.Color(0, 38, 76));
        jBtn_Salir.setFont(new java.awt.Font("Open Sans", 1, 16)); // NOI18N
        jBtn_Salir.setForeground(new java.awt.Color(229, 229, 229));
        jBtn_Salir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jBtn_Salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cl/unibiblioduocuc/img/Key-blank.png"))); // NOI18N
        jBtn_Salir.setText("Salir");
        jBtn_Salir.setName("jBtn_Salir"); // NOI18N
        jBtn_Salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtn_SalirMouseClicked(evt);
            }
        });
        jPanel9.add(jBtn_Salir, java.awt.BorderLayout.CENTER);

        jPanel5.add(jPanel9);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.8;
        jPanel1.add(jPanel5, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(jPanel1, gridBagConstraints);

        jParentPanel_VPrincipal.setBackground(new java.awt.Color(229, 229, 229));
        jParentPanel_VPrincipal.setMinimumSize(new java.awt.Dimension(500, 0));
        jParentPanel_VPrincipal.setPreferredSize(new java.awt.Dimension(500, 570));
        jParentPanel_VPrincipal.setLayout(new java.awt.CardLayout());

        jPanel_Libros.setBackground(new java.awt.Color(229, 229, 229));
        jPanel_Libros.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel_SearchBarLibros.setBackground(new java.awt.Color(229, 229, 229));
        jPanel_SearchBarLibros.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel_SearchBarLibros.setMinimumSize(new java.awt.Dimension(600, 150));
        jPanel_SearchBarLibros.setName(""); // NOI18N
        jPanel_SearchBarLibros.setPreferredSize(new java.awt.Dimension(600, 132));
        java.awt.GridBagLayout jPanel2Layout = new java.awt.GridBagLayout();
        jPanel2Layout.columnWidths = new int[] {0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0};
        jPanel2Layout.rowHeights = new int[] {0, 20, 0};
        jPanel_SearchBarLibros.setLayout(jPanel2Layout);

        jLabel2.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Búsqueda rápida: ");
        jLabel2.setToolTipText("");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        jPanel_SearchBarLibros.add(jLabel2, gridBagConstraints);

        jTxt_InputSearch.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        jTxt_InputSearch.setText("¿Qué desea buscar?");
        jTxt_InputSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTxt_InputSearchMouseClicked(evt);
            }
        });
        jTxt_InputSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxt_InputSearchActionPerformed(evt);
            }
        });
        jTxt_InputSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTxt_InputSearchKeyPressed(evt);
                jTxt_InputSearchEnterPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.6;
        jPanel_SearchBarLibros.add(jTxt_InputSearch, gridBagConstraints);

        jBtn_SubmitSearch.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        jBtn_SubmitSearch.setText("Buscar");
        jBtn_SubmitSearch.setToolTipText("");
        jBtn_SubmitSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_SubmitSearchActionPerformed(evt);
            }
        });
        jBtn_SubmitSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jBtn_SubmitSearchKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        jPanel_SearchBarLibros.add(jBtn_SubmitSearch, gridBagConstraints);

        jBtnGroup_SearchBar_Libros.add(jRadBtn_Titulo);
        jRadBtn_Titulo.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        jRadBtn_Titulo.setSelected(true);
        jRadBtn_Titulo.setText("Título");
        jRadBtn_Titulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadBtn_TituloActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel_SearchBarLibros.add(jRadBtn_Titulo, gridBagConstraints);

        jBtnGroup_SearchBar_Libros.add(jRadBtn_Autor);
        jRadBtn_Autor.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        jRadBtn_Autor.setText("Autor");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel_SearchBarLibros.add(jRadBtn_Autor, gridBagConstraints);

        jBtnGroup_SearchBar_Libros.add(jRadBtn_Isbn);
        jRadBtn_Isbn.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        jRadBtn_Isbn.setText("ISBN");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        jPanel_SearchBarLibros.add(jRadBtn_Isbn, gridBagConstraints);

        jPanel_Libros.add(jPanel_SearchBarLibros);

        jPanel_GestionLibros.setBackground(new java.awt.Color(229, 229, 229));
        jPanel_GestionLibros.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel_GestionLibros.setPreferredSize(new java.awt.Dimension(600, 100));
        jPanel_GestionLibros.setRequestFocusEnabled(false);
        java.awt.GridBagLayout jPanel_GestionLibrosLayout = new java.awt.GridBagLayout();
        jPanel_GestionLibrosLayout.columnWidths = new int[] {0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0};
        jPanel_GestionLibrosLayout.rowHeights = new int[] {0, 20, 0};
        jPanel_GestionLibros.setLayout(jPanel_GestionLibrosLayout);

        jLabel4.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Gestión de libros");
        jLabel4.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jLabel4.setMinimumSize(new java.awt.Dimension(100, 17));
        jLabel4.setVerifyInputWhenFocusTarget(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        jPanel_GestionLibros.add(jLabel4, gridBagConstraints);

        jBtn_agregar.setText("Agregar");
        jBtn_agregar.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        jBtn_agregar.setPreferredSize(new java.awt.Dimension(90, 30));
        jBtn_agregar.setVerifyInputWhenFocusTarget(false);
        jBtn_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_agregarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.weightx = 0.3;
        jPanel_GestionLibros.add(jBtn_agregar, gridBagConstraints);

        jBtn_editar.setText("Editar");
        jBtn_editar.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        jBtn_editar.setPreferredSize(new java.awt.Dimension(90, 30));
        jBtn_editar.setVerifyInputWhenFocusTarget(false);
        jBtn_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_editarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.weightx = 0.3;
        jPanel_GestionLibros.add(jBtn_editar, gridBagConstraints);

        jBtn_eliminar.setText("Eliminar");
        jBtn_eliminar.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        jBtn_eliminar.setPreferredSize(new java.awt.Dimension(90, 30));
        jBtn_eliminar.setVerifyInputWhenFocusTarget(false);
        jBtn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_eliminarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.weightx = 0.3;
        jPanel_GestionLibros.add(jBtn_eliminar, gridBagConstraints);

        jPanel_Libros.add(jPanel_GestionLibros);

        jPanel_CatalogoLibros.setBackground(new java.awt.Color(229, 229, 229));
        jPanel_CatalogoLibros.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel_CatalogoLibros.setMinimumSize(new java.awt.Dimension(120, 280));
        jPanel_CatalogoLibros.setPreferredSize(new java.awt.Dimension(600, 280));
        java.awt.GridBagLayout jPanel_CatalogoLibrosLayout = new java.awt.GridBagLayout();
        jPanel_CatalogoLibrosLayout.columnWidths = new int[] {0, 10, 0, 10, 0};
        jPanel_CatalogoLibrosLayout.rowHeights = new int[] {0, 10, 0};
        jPanel_CatalogoLibros.setLayout(jPanel_CatalogoLibrosLayout);

        jLabel5.setText("Catálogo de Libros");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.1;
        jPanel_CatalogoLibros.add(jLabel5, gridBagConstraints);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setMinimumSize(new java.awt.Dimension(500, 240));
        jScrollPane1.setName(""); // NOI18N
        jScrollPane1.setPreferredSize(new java.awt.Dimension(500, 240));
        jScrollPane1.setRequestFocusEnabled(false);

        jTable_CatLibros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                { new Integer(1), "Cien años de soledad", "Gabriel García Márquez", "Editorial Sudamericana",  new Integer(1967), "Realismo mágico", "978-84-663-0344-6", "Disponible", "Clásicos"}
            },
            new String [] {
                "ID", "Título", "Nombre Autor", "Editorial", "Año", "Género", "ISBN", "Estado", "Colección"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_CatLibros.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTable_CatLibros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_CatLibrosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_CatLibros);
        if (jTable_CatLibros.getColumnModel().getColumnCount() > 0) {
            jTable_CatLibros.getColumnModel().getColumn(0).setMinWidth(100);
            jTable_CatLibros.getColumnModel().getColumn(1).setMinWidth(100);
            jTable_CatLibros.getColumnModel().getColumn(2).setMinWidth(100);
            jTable_CatLibros.getColumnModel().getColumn(3).setMinWidth(100);
            jTable_CatLibros.getColumnModel().getColumn(4).setMinWidth(100);
            jTable_CatLibros.getColumnModel().getColumn(5).setMinWidth(100);
            jTable_CatLibros.getColumnModel().getColumn(6).setMinWidth(100);
            jTable_CatLibros.getColumnModel().getColumn(7).setMinWidth(100);
            jTable_CatLibros.getColumnModel().getColumn(8).setMinWidth(100);
        }

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weighty = 0.8;
        jPanel_CatalogoLibros.add(jScrollPane1, gridBagConstraints);

        jPanel_Libros.add(jPanel_CatalogoLibros);

        jButton4.setText("Refrescar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel_Libros.add(jButton4);

        jParentPanel_VPrincipal.add(jPanel_Libros, "card1");

        jPanel_Prestamos.setBackground(new java.awt.Color(229, 229, 229));
        jPanel_Prestamos.setLayout(new java.awt.BorderLayout());

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Préstamos");
        jPanel_Prestamos.add(jLabel3, java.awt.BorderLayout.CENTER);

        jParentPanel_VPrincipal.add(jPanel_Prestamos, "card3");

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.7;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(jParentPanel_VPrincipal, gridBagConstraints);

        jMenu1.setText("Archivo");

        jMenuItem2.setText("Añadir libro");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Realizar préstamo");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);
        jMenu1.add(jSeparator1);

        jMenuItem12.setText("Cerrar sesión");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem12);

        jMenuItem4.setText("Cerrar");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Editar");

        jMenuItem5.setText("Editar libro");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuItem6.setText("Editar préstamo");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem6);
        jMenu2.add(jSeparator2);

        jMenuItem9.setText("Devolver Libro");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem9);
        jMenu2.add(jSeparator3);

        jMenuItem7.setText("Eliminar libro");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem7);

        jMenuItem8.setText("Eliminar préstamo");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem8);

        jMenuBar1.add(jMenu2);

        jMenu_Help.setText("Ayuda");

        jMenuItem_About.setText("Acerca de");
        jMenuItem_About.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_AboutActionPerformed(evt);
            }
        });
        jMenu_Help.add(jMenuItem_About);

        jMenuBar1.add(jMenu_Help);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(800, 650));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        ControladorPrincipal contP = new ControladorPrincipal();
        contP.handleAgregar(this.bd);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        JOptionPane.showMessageDialog(null, "Acción aún no implementada.", "Información", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed

        System.exit(0);

    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        int response = JOptionPane.showConfirmDialog(null, "¿Seguro que desea salir?", "Confirmación", 2, JOptionPane.YES_NO_OPTION);
        if (response == JOptionPane.YES_OPTION) {
            dispose();
            VistaLogin vl = new VistaLogin();
            vl.setVisible(true);
        }
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jMenuItem_AboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_AboutActionPerformed
        String text = "<html><body style='text-align: center; background-color:#D6D9DF;'>"
                + "<p>Programa realizado con fines educativos para la asignatura <br>"
                + "<strong>Desarrollo de Software de Escritorio</strong> DuocUC.</p>"
                + "<p>Para revisar la documentación del programa, visita <br>"
                + "<a href='https://github.com/Gab-Serrano/UniBiblioDuocUC' style='color: blue;'>github.com/Gab-Serrano/UniBiblioDuocUC</a></p>"
                + "<p>Autor: <strong>Gabriel Serrano - Ayudante PGY2121 DuocUC</strong><br>"
                + "<a href='https://github.com/Gab-Serrano' style='color: blue;'> github.com/Gab-Serrano</a></p>"
                + "</body></html>";
        JEditorPane editorPane = new JEditorPane("text/html", text);

        editorPane.setEditable(false);
        editorPane.setOpaque(false);
        editorPane.setBackground(new Color(0, 0, 0, 0));

        editorPane.addHyperlinkListener(e -> {
            if (e.getEventType().toString().equals("ACTIVATED")) {
                try {
                    Desktop.getDesktop().browse(new URI(e.getURL().toString()));
                } catch (IOException | URISyntaxException ex) {
                    ex.printStackTrace();
                }
            }
        });

        // Para que se vea como un enlace de mano al pasar por encima
        editorPane.setCursor(new Cursor(Cursor.HAND_CURSOR));

        JOptionPane.showMessageDialog(null, editorPane, "Mensaje con enlace", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jMenuItem_AboutActionPerformed

    private void jBtn_LibrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtn_LibrosMouseClicked
        btnLblClicked(evt);
    }//GEN-LAST:event_jBtn_LibrosMouseClicked

    private void jBtn_PrestamosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtn_PrestamosMouseClicked
        btnLblClicked(evt);
    }//GEN-LAST:event_jBtn_PrestamosMouseClicked

    private void jTxt_InputSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTxt_InputSearchMouseClicked
        if (jTxt_InputSearch.getText().equals("¿Qué desea buscar?")) {
            jTxt_InputSearch.setText("");
        }
    }//GEN-LAST:event_jTxt_InputSearchMouseClicked

    private void jTxt_InputSearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxt_InputSearchKeyPressed
        if (jTxt_InputSearch.getText().equals("¿Qué desea buscar?")) {
            jTxt_InputSearch.setText("");
        }
    }//GEN-LAST:event_jTxt_InputSearchKeyPressed

    private void jTxt_InputSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxt_InputSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxt_InputSearchActionPerformed

    private void jRadBtn_TituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadBtn_TituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadBtn_TituloActionPerformed

    private void jBtn_SubmitSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_SubmitSearchActionPerformed
        ControladorPrincipal contLibros = new ControladorPrincipal();
        String query = jTxt_InputSearch.getText();
        String type = getSelectedRadButton(radioButtons);

        fillSearchedBooks(contLibros.buscarLibroPorQuery(query, type, bd));
        ;
    }//GEN-LAST:event_jBtn_SubmitSearchActionPerformed

    private void jBtn_SubmitSearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jBtn_SubmitSearchKeyPressed

    }//GEN-LAST:event_jBtn_SubmitSearchKeyPressed

    private void jTxt_InputSearchEnterPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxt_InputSearchEnterPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jBtn_SubmitSearch.doClick();  // Simula un clic en el botón al presionar Enter
        }
    }//GEN-LAST:event_jTxt_InputSearchEnterPressed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        fillAllBooks();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jBtn_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_agregarActionPerformed
        ControladorPrincipal contP = new ControladorPrincipal();
        contP.handleAgregar(this.bd);
    }//GEN-LAST:event_jBtn_agregarActionPerformed

    private void jBtn_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_editarActionPerformed
        if (libroId != -1) {
            ControladorPrincipal contP = new ControladorPrincipal();
            contP.handleEditar(this.bd, this.libroId);
        } else {
            JOptionPane.showMessageDialog(null, "Debe seleccionar un libro de la lista.", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }
        fillAllBooks();
    }//GEN-LAST:event_jBtn_editarActionPerformed

    private void jTable_CatLibrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_CatLibrosMouseClicked
        int selectedRow = jTable_CatLibros.getSelectedRow();
        this.libroId = Integer.parseInt(jTable_CatLibros.getValueAt(selectedRow, 0).toString());
    }//GEN-LAST:event_jTable_CatLibrosMouseClicked

    private void jBtn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_eliminarActionPerformed
        if (libroId != -1) {
            ControladorPrincipal contP = new ControladorPrincipal();
            Libro libroEliminar = contP.obtenerLibroPorId(this.libroId, this.bd);
            String titulo = libroEliminar.getTitulo();
            int response = JOptionPane.showConfirmDialog(null, "¿Seguro que desea eliminar " + titulo + "?", "Confirmación", 2, JOptionPane.YES_NO_OPTION);
            if (response == JOptionPane.YES_OPTION) {
                contP.eliminarLibro(libroId, this.bd);
                fillAllBooks();
            }

        } else {
            JOptionPane.showMessageDialog(null, "Debe seleccionar un libro de la lista.", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jBtn_eliminarActionPerformed

    private void jBtn_SalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtn_SalirMouseClicked
        btnLblClicked(evt);
    }//GEN-LAST:event_jBtn_SalirMouseClicked

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        JOptionPane.showMessageDialog(null, "Acción aún no implementada.", "Información", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        if (libroId != -1) {
            ControladorPrincipal contP = new ControladorPrincipal();
            contP.handleEditar(this.bd, this.libroId);
        } else {
            JOptionPane.showMessageDialog(null, "Debe seleccionar un libro de la lista.", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }
        fillAllBooks();
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        JOptionPane.showMessageDialog(null, "Acción aún no implementada.", "Información", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        if (libroId != -1) {
            ControladorPrincipal contP = new ControladorPrincipal();
            Libro libroEliminar = contP.obtenerLibroPorId(this.libroId, this.bd);
            String titulo = libroEliminar.getTitulo();
            int response = JOptionPane.showConfirmDialog(null, "¿Seguro que desea eliminar " + titulo + "?", "Confirmación", 2, JOptionPane.YES_NO_OPTION);
            if (response == JOptionPane.YES_OPTION) {
                contP.eliminarLibro(libroId, this.bd);
                fillAllBooks();
            }

        } else {
            JOptionPane.showMessageDialog(null, "Debe seleccionar un libro de la lista.", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        JOptionPane.showMessageDialog(null, "Acción aún no implementada.", "Información", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    /* ---------------- Métodos customizados --------------------- */
    public void setBiblioLogeado(Bibliotecario biblioLogeado) {
        this.biblioLogeado = biblioLogeado;
    }

    private void setNombreEmpleadoUI() {
        try {
            String nomBiblioLogeado = this.biblioLogeado.getNombre() + " " + this.biblioLogeado.getApellido();
            jLabel_NomEmpleado.setText(nomBiblioLogeado);
        } catch (Exception e) {
            System.out.println("Exception = " + e);
        }
    }

    private ImageIcon getIconBtn(String path) {
        try {
            ImageIcon icon = new ImageIcon(getClass().getResource(path));
            return icon;
        } catch (Exception ex) {
            ex.printStackTrace();
        }

        return new ImageIcon();
    }

    private void setActive(JPanel vistaPanel, JPanel panelBtn, JLabel label) {
        //Set panel
        jParentPanel_VPrincipal.add(vistaPanel);
        jParentPanel_VPrincipal.repaint();
        jParentPanel_VPrincipal.revalidate();

        //Set Colores
        panelBtn.setBackground(primaryBg);
        label.setForeground(secondaryBg);

        //Set Icon
        String path = "/cl/unibiblioduocuc/img/" + label.getName() + "-icon-fill.png";
        label.setIcon(getIconBtn(path));

    }

    private void setInactive(JPanel panelBtn, JLabel label) {
        //Set Colores
        panelBtn.setBackground(secondaryBtn);
        label.setForeground(primaryBg);

        //Set Icon
        String path = "/cl/unibiblioduocuc/img/" + label.getName() + "-icon-blank.png";
        label.setIcon(getIconBtn(path));
    }

    private void resetAllButtonsAndPanels() {
        jParentPanel_VPrincipal.removeAll();

        setInactive(jPanelBtn_Libros, jBtn_Libros);
        setInactive(jPanelBtn_Prestamos, jBtn_Prestamos);
    }

    private void btnLblClicked(java.awt.event.MouseEvent evt) {
        JLabel clickedLabel = (JLabel) evt.getSource();

        switch (clickedLabel.getName()) {
            case "jBtn_Libros":
                resetAllButtonsAndPanels();
                setActive(jPanel_Libros, jPanelBtn_Libros, jBtn_Libros);
                break;
            case "jBtn_Prestamos":
                resetAllButtonsAndPanels();
                setActive(jPanel_Prestamos, jPanelBtn_Prestamos, jBtn_Prestamos);
                break;
            case "jBtn_Salir":
                int response = JOptionPane.showConfirmDialog(null, "¿Seguro que desea salir?", "Confirmación", 2, JOptionPane.YES_NO_OPTION);
                if (response == JOptionPane.YES_OPTION) {
                    dispose();
                    VistaLogin vl = new VistaLogin();
                    vl.setVisible(true);
                }
                break;
            default:
                throw new AssertionError();
        }
    }

    private void fillAllBooks() {
        ControladorPrincipal contLibros = new ControladorPrincipal();

        DefaultTableModel model = (DefaultTableModel) jTable_CatLibros.getModel();
        model.setRowCount(0);

        for (Libro libro : contLibros.obtenerLibros(bd)) {
            Object[] rowData = new Object[]{
                libro.getId(),
                libro.getTitulo(),
                libro.getNomAutor(),
                libro.getEditorial(),
                libro.getAnnoPublicacion(),
                libro.getGenero(),
                libro.getIsbn(),
                libro.getEstado(),
                libro.getColeccion()
            };
            model.addRow(rowData);
        }
    }

    private void fillSearchedBooks(ArrayList<Libro> librosBuscados) {
        DefaultTableModel model = (DefaultTableModel) jTable_CatLibros.getModel();
        model.setRowCount(0);

        for (Libro libro : librosBuscados) {
            Object[] rowData = new Object[]{
                libro.getId(),
                libro.getTitulo(),
                libro.getNomAutor(),
                libro.getEditorial(),
                libro.getAnnoPublicacion(),
                libro.getGenero(),
                libro.getIsbn(),
                libro.getEstado(),
                libro.getEstado(),
                libro.getColeccion()
            };
            model.addRow(rowData);
        }

    }

    private void enlistarRadButtons(JRadioButton option1, JRadioButton option2, JRadioButton option3) {
        radioButtons.add(option1);
        radioButtons.add(option2);
        radioButtons.add(option3);
    }

    private String getSelectedRadButton(ArrayList<JRadioButton> radioButtons) {
        for (JRadioButton radioButton : radioButtons) {
            if (radioButton.isSelected()) {
                return removeTildes(radioButton.getText());
            }
        }
        return "";
    }

    private String removeTildes(String input) {
        input = input.toLowerCase();  // Convertir a minúsculas
        input = input.replace('á', 'a');
        input = input.replace('é', 'e');
        input = input.replace('í', 'i');
        input = input.replace('ó', 'o');
        input = input.replace('ú', 'u');
        input = input.replace('ü', 'u');
        input = input.replace('ñ', 'n');
        // Agrega más reemplazos si es necesario
        return input;
    }

    private int getFilaCatalogo(int indx) {
        return indx;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {;
                new VistaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup jBtnGroup_SearchBar_Libros;
    private javax.swing.JLabel jBtn_Libros;
    private javax.swing.JLabel jBtn_Prestamos;
    private javax.swing.JLabel jBtn_Salir;
    private javax.swing.JButton jBtn_SubmitSearch;
    private javax.swing.JButton jBtn_agregar;
    private javax.swing.JButton jBtn_editar;
    private javax.swing.JButton jBtn_eliminar;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel_NomEmpleado;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JMenuItem jMenuItem_About;
    private javax.swing.JMenu jMenu_Help;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jPanelBtn_Libros;
    private javax.swing.JPanel jPanelBtn_Prestamos;
    private javax.swing.JPanel jPanel_CatalogoLibros;
    private javax.swing.JPanel jPanel_GestionLibros;
    private javax.swing.JPanel jPanel_Libros;
    private javax.swing.JPanel jPanel_Prestamos;
    private javax.swing.JPanel jPanel_SearchBarLibros;
    private javax.swing.JPanel jParentPanel_VPrincipal;
    private javax.swing.JRadioButton jRadBtn_Autor;
    private javax.swing.JRadioButton jRadBtn_Isbn;
    private javax.swing.JRadioButton jRadBtn_Titulo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JTable jTable_CatLibros;
    private javax.swing.JTextField jTxt_InputSearch;
    // End of variables declaration//GEN-END:variables
}
