/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cl.unibiblioduocuc.vista.gestionlibros;

import cl.unibiblioduocuc.controlador.ControladorPrincipal;
import cl.unibiblioduocuc.modelo.Libro;
import cl.unibiblioduocuc.modelo.TestBD;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author Gabriel
 */
public class VistaEditarLibros extends javax.swing.JFrame {

    private TestBD bd;
    private Libro libro;

    /**
     * Creates new form VistaEditarLibros
     */
    public VistaEditarLibros(TestBD bd, Libro libro) {
        this.bd = bd;
        this.libro = libro;
        initComponents();
        setComboBox();
        setFieldsEditar(this.libro);
        System.out.println("");
    }

    public VistaEditarLibros() {
        this.bd = new TestBD();
        this.libro = new Libro(01, "Frankenstein", "Mery Shelly", "Porrua", 1863, "Ciencia Ficción", "87654345", "Prestado", "General");
        initComponents();
        setComboBox();
        setFieldsEditar(this.libro);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTxt_titulo = new javax.swing.JTextField();
        jTxt_autor = new javax.swing.JTextField();
        jTxt_anno = new javax.swing.JTextField();
        jTxt_editorial = new javax.swing.JTextField();
        jTxt_genero = new javax.swing.JTextField();
        jTxt_isbn = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jBtn_Editar = new javax.swing.JButton();
        jBtn_cancelar = new javax.swing.JButton();
        jCmbBox_coleccion = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("UniBiblio - Agregar libros");

        jPanel1.setLayout(new java.awt.GridBagLayout());

        jPanel3.setMinimumSize(new java.awt.Dimension(0, 0));
        jPanel3.setPreferredSize(new java.awt.Dimension(0, 0));
        java.awt.GridBagLayout jPanel3Layout = new java.awt.GridBagLayout();
        jPanel3Layout.columnWidths = new int[] {0, 20, 0, 20, 0};
        jPanel3Layout.rowHeights = new int[] {0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0};
        jPanel3.setLayout(jPanel3Layout);

        jLabel1.setText("Título:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel3.add(jLabel1, gridBagConstraints);

        jLabel3.setText("Autor:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel3.add(jLabel3, gridBagConstraints);

        jLabel4.setText("Editorial:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel3.add(jLabel4, gridBagConstraints);

        jLabel5.setText("Año:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel3.add(jLabel5, gridBagConstraints);

        jLabel6.setText("Género:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel3.add(jLabel6, gridBagConstraints);

        jLabel7.setText("ISBN:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel3.add(jLabel7, gridBagConstraints);

        jLabel8.setText("Colección:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel3.add(jLabel8, gridBagConstraints);

        jTxt_titulo.setMinimumSize(new java.awt.Dimension(150, 22));
        jTxt_titulo.setPreferredSize(new java.awt.Dimension(150, 25));
        jTxt_titulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxt_tituloActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 2;
        gridBagConstraints.ipady = 3;
        jPanel3.add(jTxt_titulo, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 2;
        gridBagConstraints.ipady = 2;
        jPanel3.add(jTxt_autor, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 2;
        gridBagConstraints.ipady = 2;
        jPanel3.add(jTxt_anno, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 2;
        gridBagConstraints.ipady = 2;
        jPanel3.add(jTxt_editorial, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 2;
        gridBagConstraints.ipady = 2;
        jPanel3.add(jTxt_genero, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 2;
        gridBagConstraints.ipady = 2;
        jPanel3.add(jTxt_isbn, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Open Sans", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Agregar Libros");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel2.setMaximumSize(new java.awt.Dimension(2000, 2000));
        jLabel2.setMinimumSize(new java.awt.Dimension(100, 50));
        jLabel2.setOpaque(true);
        jLabel2.setPreferredSize(new java.awt.Dimension(100, 50));
        jLabel2.setVerifyInputWhenFocusTarget(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel3.add(jLabel2, gridBagConstraints);

        jBtn_Editar.setText("Editar");
        jBtn_Editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_EditarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 18;
        jPanel3.add(jBtn_Editar, gridBagConstraints);

        jBtn_cancelar.setText("Cancelar");
        jBtn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_cancelarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 18;
        jPanel3.add(jBtn_cancelar, gridBagConstraints);

        jCmbBox_coleccion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jCmbBox_coleccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCmbBox_coleccionActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel3.add(jCmbBox_coleccion, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.7;
        jPanel1.add(jPanel3, gridBagConstraints);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(389, 453));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTxt_tituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxt_tituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxt_tituloActionPerformed

    private void jBtn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_cancelarActionPerformed
        dispose();
    }//GEN-LAST:event_jBtn_cancelarActionPerformed

    private void jBtn_EditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_EditarActionPerformed
        Libro libroEditado = setLibroObject();
        ControladorPrincipal contP = new ControladorPrincipal(this.bd);
        contP.guardarCambios(libroEditado);
        dispose();
    }//GEN-LAST:event_jBtn_EditarActionPerformed

    private void jCmbBox_coleccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCmbBox_coleccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCmbBox_coleccionActionPerformed

    private void setFieldsEditar(Libro libro) {
        jTxt_titulo.setText(libro.getTitulo());
        jTxt_autor.setText(libro.getNomAutor());
        jTxt_editorial.setText(libro.getEditorial());
        jTxt_anno.setText(String.valueOf(libro.getAnnoPublicacion()));
        jTxt_genero.setText(libro.getGenero());
        jTxt_isbn.setText(libro.getIsbn());
        jCmbBox_coleccion.setSelectedItem(libro.getColeccion());
    }

    private void setComboBox() {
        ControladorPrincipal contLib = new ControladorPrincipal();

        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
        for (String item : contLib.obtenerColecciones(this.bd)) {
            model.addElement(item);
        }

        jCmbBox_coleccion.setModel(model);
    }

    private Libro setLibroObject() {
        Libro libroPorEditar = new Libro();

        libroPorEditar.setId(this.libro.getId());
        libroPorEditar.setTitulo(jTxt_titulo.getText());
        libroPorEditar.setNomAutor(jTxt_autor.getText());
        libroPorEditar.setEditorial(jTxt_editorial.getText());
        int anno = (int) Integer.valueOf(jTxt_anno.getText());
        libroPorEditar.setAnnoPublicacion(anno);
        libroPorEditar.setGenero(jTxt_genero.getText());
        libroPorEditar.setIsbn(jTxt_isbn.getText());
        libroPorEditar.setEstado("Disponible");
        libroPorEditar.setColeccion((String) jCmbBox_coleccion.getSelectedItem());

        return libroPorEditar;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaEditarLibros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaEditarLibros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaEditarLibros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaEditarLibros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaEditarLibros().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtn_Editar;
    private javax.swing.JButton jBtn_cancelar;
    private javax.swing.JComboBox<String> jCmbBox_coleccion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTxt_anno;
    private javax.swing.JTextField jTxt_autor;
    private javax.swing.JTextField jTxt_editorial;
    private javax.swing.JTextField jTxt_genero;
    private javax.swing.JTextField jTxt_isbn;
    private javax.swing.JTextField jTxt_titulo;
    // End of variables declaration//GEN-END:variables
}
